// Copyright (c) Weihan Li. All rights reserved.
// Licensed under the Apache license.

using System.Runtime.CompilerServices;
using WeihanLi.Common.Abstractions;
using WeihanLi.Common.Compressor;
using WeihanLi.Common.Helpers;
using WeihanLi.Common.Helpers.Combinatorics;
using WeihanLi.Common.Helpers.PeriodBatching;
using WeihanLi.Common.Otp;
using WeihanLi.Common.Services;
using WeihanLi.Extensions;

[assembly: TypeForwardedTo(typeof(IDataCompressor))]
[assembly: TypeForwardedTo(typeof(NullDataCompressor))]
[assembly: TypeForwardedTo(typeof(GZipDataCompressor))]
[assembly: TypeForwardedTo(typeof(IProperties))]
[assembly: TypeForwardedTo(typeof(IStringProperties))]
[assembly: TypeForwardedTo(typeof(BoundedConcurrentQueue<>))]
[assembly: TypeForwardedTo(typeof(BoundedQueueFullMode))]
[assembly: TypeForwardedTo(typeof(TotpHelper))]
[assembly: TypeForwardedTo(typeof(OtpHashAlgorithm))]
[assembly: TypeForwardedTo(typeof(TotpOptions))]
[assembly: TypeForwardedTo(typeof(Totp))]
[assembly: TypeForwardedTo(typeof(ITotpService))]
[assembly: TypeForwardedTo(typeof(TotpServiceExtensions))]
[assembly: TypeForwardedTo(typeof(TotpService))]
[assembly: TypeForwardedTo(typeof(GenerateOption))]
[assembly: TypeForwardedTo(typeof(Combinations<>))]
[assembly: TypeForwardedTo(typeof(Permutations<>))]
[assembly: TypeForwardedTo(typeof(Variations<>))]
[assembly: TypeForwardedTo(typeof(PeriodicBatching<>))]
[assembly: TypeForwardedTo(typeof(NullDisposable))]
[assembly: TypeForwardedTo(typeof(DisposableAction))]
[assembly: TypeForwardedTo(typeof(DisposableBase))]
[assembly: TypeForwardedTo(typeof(StreamMessage<>))]
[assembly: TypeForwardedTo(typeof(StreamInfo<>))]
[assembly: TypeForwardedTo(typeof(StreamGroupInfo<>))]
[assembly: TypeForwardedTo(typeof(IStream<>))]
[assembly: TypeForwardedTo(typeof(InMemoryStream<>))]
[assembly: TypeForwardedTo(typeof(CommandLineParser))]
[assembly: TypeForwardedTo(typeof(LineParseOptions))]
[assembly: TypeForwardedTo(typeof(EnvHelper))]
[assembly: TypeForwardedTo(typeof(TypeHelper))]
[assembly: TypeForwardedTo(typeof(ValidateHelper))]
[assembly: TypeForwardedTo(typeof(ValueStopwatch))]
[assembly: TypeForwardedTo(typeof(ProfilerStopper))]
[assembly: TypeForwardedTo(typeof(StopwatchStopper))]
[assembly: TypeForwardedTo(typeof(ProfilerHelper))]
[assembly: TypeForwardedTo(typeof(IProfiler))]
[assembly: TypeForwardedTo(typeof(StopwatchProfiler))]
[assembly: TypeForwardedTo(typeof(ICancellationTokenProvider))]
[assembly: TypeForwardedTo(typeof(NullCancellationTokenProvider))]
[assembly: TypeForwardedTo(typeof(IIdGenerator))]
[assembly: TypeForwardedTo(typeof(GuidIdGenerator))]
[assembly: TypeForwardedTo(typeof(SequentialGuidIdGenerator))]
[assembly: TypeForwardedTo(typeof(IScope))]
[assembly: TypeForwardedTo(typeof(NullScope))]
[assembly: TypeForwardedTo(typeof(ITenantProvider))]
[assembly: TypeForwardedTo(typeof(TenantIdProviderExtensions))]
[assembly: TypeForwardedTo(typeof(IUserIdProvider))]
[assembly: TypeForwardedTo(typeof(UserIdProviderExtensions))]
[assembly: TypeForwardedTo(typeof(EnvironmentUserIdProvider))]
[assembly: TypeForwardedTo(typeof(DelegateUserIdProvider))]
[assembly: TypeForwardedTo(typeof(IWrapper<>))]
[assembly: TypeForwardedTo(typeof(Wrapper<>))]
[assembly: TypeForwardedTo(typeof(DictionaryExtension))]
[assembly: TypeForwardedTo(typeof(EnumerableExtension))]
[assembly: TypeForwardedTo(typeof(PropertiesExtensions))]
